export default {
	"nodes": [
        {"id": "Lockman-Bechtelar", "group": 1},
        {"id": "Latvia", "group": 2},
        {"id": "Göteborg DC", "group": 3},
        {"id": "EV Car Battery", "group": 4},
        {"id": "Wrocław Production", "group": 5},
        {"id": "Mohr Inc", "group": 1},
        {"id": "France", "group": 2},
        {"id": "Lyon DC", "group": 3},
        {"id": "Antwerp Production", "group": 5},
        {"id": "Gusikowski LLC", "group": 1},
        {"id": "Poland", "group": 2},
        {"id": "Wrocław DC", "group": 3},
        {"id": "Ryan-Lesch", "group": 1},
        {"id": "Germany", "group": 2},
        {"id": "Antwerp DC", "group": 3},
        {"id": "Denesik-Lesch", "group": 1},
        {"id": "Croatia", "group": 2},
        {"id": "Donnelly Group", "group": 1},
        {"id": "Greece", "group": 2},
        {"id": "Powlowski Group", "group": 1},
        {"id": "Kuvalis-Rogahn", "group": 1},
        {"id": "Netherlands", "group": 2},
        {"id": "Runolfsson-Braun", "group": 1},
        {"id": "Feeney-Miller", "group": 1},
        {"id": "Home Battery", "group": 4},
        {"id": "Little-Ankunding", "group": 1},
        {"id": "Jast-West", "group": 1},
        {"id": "Sipes-Haag", "group": 1},
        {"id": "Czech Republic", "group": 2},
        {"id": "Lyon Production", "group": 5},
        {"id": "Toy-Beatty", "group": 1},
        {"id": "Quitzon Group", "group": 1},
        {"id": "Kuvalis Inc", "group": 1},
        {"id": "Ledner-Gerlach", "group": 1},
        {"id": "Okuneva Inc", "group": 1},
        {"id": "Kiehn Inc", "group": 1},
        {"id": "McLaughlin-Stiedemann", "group": 1},
        {"id": "Zboncak-Dare", "group": 1},
        {"id": "Grady-Shanahan", "group": 1},
        {"id": "Kemmer-Pouros", "group": 1},
        {"id": "Konopelski LLC", "group": 1},
        {"id": "Collins Group", "group": 1},
        {"id": "Wintheiser-Torphy", "group": 1},
        {"id": "Spencer and Sons", "group": 1},
        {"id": "Sanford LLC", "group": 1},
        {"id": "McCullough LLC", "group": 1},
        {"id": "Durgan-Gleichner", "group": 1},
        {"id": "Boyle-Kunze", "group": 1},
        {"id": "Trantow and Sons", "group": 1},
        {"id": "Will Inc", "group": 1},
        {"id": "Bergnaum-Bosco", "group": 1},
        {"id": "Daniel and Sons", "group": 1},
        {"id": "Hayes Inc", "group": 1},
        {"id": "Rowe Inc", "group": 1},
        {"id": "Baumbach-Price", "group": 1},
        {"id": "Lueilwitz-Langworth", "group": 1},
        {"id": "Reinger and Sons", "group": 1},
        {"id": "Howell-Graham", "group": 1},
        {"id": "Hills LLC", "group": 1},
        {"id": "Luettgen-Nikolaus", "group": 1},
        {"id": "Batz Inc", "group": 1},
        {"id": "Boehm-Bayer", "group": 1},
        {"id": "Lowe Inc", "group": 1},
        {"id": "Schuppe Inc", "group": 1},
        {"id": "Nitzsche LLC", "group": 1},
        {"id": "Green-Kuphal", "group": 1}
      ],
      "links": [
        {"source": "Lockman-Bechtelar", "target": "Latvia", "value": 5},
        {"source": "Latvia", "target": "Göteborg DC", "value": 5},
        {"source": "Göteborg DC", "target": "EV Car Battery", "value": 5},
        {"source": "EV Car Battery", "target": "Wrocław Production", "value": 5},
        {"source": "Mohr Inc", "target": "France", "value": 5},
        {"source": "France", "target": "Lyon DC", "value": 5},
        {"source": "Lyon DC", "target": "EV Car Battery", "value": 5},
        {"source": "EV Car Battery", "target": "Antwerp Production", "value": 5},
        {"source": "Gusikowski LLC", "target": "Poland", "value": 5},
        {"source": "Poland", "target": "Wrocław DC", "value": 5},
        {"source": "Wrocław DC", "target": "EV Car Battery", "value": 5},
        {"source": "EV Car Battery", "target": "Wrocław Production", "value": 5},
        {"source": "Ryan-Lesch", "target": "Germany", "value": 5},
        {"source": "Germany", "target": "Antwerp DC", "value": 5},
        {"source": "Antwerp DC", "target": "EV Car Battery", "value": 5},
        {"source": "EV Car Battery", "target": "Antwerp Production", "value": 5},
        {"source": "Denesik-Lesch", "target": "Croatia", "value": 5},
        {"source": "Donnelly Group", "target": "Greece", "value": 5},
        {"source": "Powlowski Group", "target": "Kuvalis-Rogahn", "value": 5},
        {"source": "Kuvalis-Rogahn", "target": "Netherlands", "value": 5},
        {"source": "Runolfsson-Braun", "target": "Feeney-Miller", "value": 5},
        {"source": "Feeney-Miller", "target": "Home Battery", "value": 5},
        {"source": "Jast-West", "target": "Little-Ankunding", "value": 5},
        {"source": "Sipes-Haag", "target": "Czech Republic", "value": 5},
        {"source": "Czech Republic", "target": "Lyon Production", "value": 5},
        {"source": "Toy-Beatty", "target": "Quitzon Group", "value": 5},
        {"source": "Quitzon Group", "target": "Kuvalis Inc", "value": 5},
        {"source": "Kuvalis Inc", "target": "Ledner-Gerlach", "value": 5},
        {"source": "Ledner-Gerlach", "target": "Okuneva Inc", "value": 5},
        {"source": "Okuneva Inc", "target": "Kiehn Inc", "value": 5},
        {"source": "Kiehn Inc", "target": "McLaughlin-Stiedemann", "value": 5},
        {"source": "McLaughlin-Stiedemann", "target": "Zboncak-Dare", "value": 5},
        {"source": "Zboncak-Dare", "target": "Grady-Shanahan", "value": 5},
        {"source": "Grady-Shanahan", "target": "Kemmer-Pouros", "value": 5},
        {"source": "Kemmer-Pouros", "target": "Konopelski LLC", "value": 5},
        {"source": "Konopelski LLC", "target": "Collins Group", "value": 5},
        {"source": "Collins Group", "target": "Wintheiser-Torphy", "value": 5},
        {"source": "Wintheiser-Torphy", "target": "Spencer and Sons", "value": 5},
        {"source": "Spencer and Sons", "target": "Sanford LLC", "value": 5},
        {"source": "Sanford LLC", "target": "McCullough LLC", "value": 5},
        {"source": "McCullough LLC", "target": "Durgan-Gleichner", "value": 5},
        {"source": "Durgan-Gleichner", "target": "Boyle-Kunze", "value": 5},
        {"source": "Boyle-Kunze", "target": "Trantow and Sons", "value": 5},
        {"source": "Trantow and Sons", "target": "Will Inc", "value": 5},
        {"source": "Will Inc", "target": "Bergnaum-Bosco", "value": 5},
        {"source": "Bergnaum-Bosco", "target": "Daniel and Sons", "value": 5},
        {"source": "Daniel and Sons", "target": "Hayes Inc", "value": 5},
        {"source": "Hayes Inc", "target": "Rowe Inc", "value": 5},
        {"source": "Rowe Inc", "target": "Baumbach-Price", "value": 5},
        {"source": "Baumbach-Price", "target": "Lueilwitz-Langworth", "value": 5},
        {"source": "Lueilwitz-Langworth", "target": "Reinger and Sons", "value": 5},
        {"source": "Reinger and Sons", "target": "Howell-Graham", "value": 5},
        {"source": "Howell-Graham", "target": "Hills LLC", "value": 5},
        {"source": "Hills LLC", "target": "Luettgen-Nikolaus", "value": 5},
        {"source": "Luettgen-Nikolaus", "target": "Batz Inc", "value": 5},
        {"source": "Batz Inc", "target": "Boehm-Bayer", "value": 5},
        {"source": "Boehm-Bayer", "target": "Lowe Inc", "value": 5},
        {"source": "Lowe Inc", "target": "Schuppe Inc", "value": 5},
        {"source": "Schuppe Inc", "target": "Nitzsche LLC", "value": 5},
        {"source": "Nitzsche LLC", "target": "Green-Kuphal", "value": 5}
      ]
    }